markdown:               kramdown
highlighter:            rouge
permalink:              /:categories/:title.html
relative_permalinks:    false
title:                  'Soner'
description:            'Simplicity is the ultimate sophistication'
baseurl:                '/'
url:                    'https://www.soner.dev'
paginate:               20
destination:		./docs
plugins:
    - jekyll-feed
    - jekyll-sass-converter
    - jekyll-sitemap
    - jekyll-paginate
    - jekyll-archives
sass:
    style: compressed
exclude:
    - poole
    - hyde
    - submodule.sh
    - build.sh
    - .sass-cache
    - README.md
jekyll-archives:
    enabled:
        - categories
    layout: category
    permalinks:
        category: /:name/index.html
